-- 관리자 쇼핑몰 schema (H2 2.4)
-- 금액은 원 단위 정수, 시각은 Asia/Seoul 기준 TIMESTAMP WITH TIME ZONE

CREATE TABLE members (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)  NOT NULL,
    email         VARCHAR(100) NOT NULL UNIQUE,
    grade         VARCHAR(20)  NOT NULL,
    status        VARCHAR(20)  NOT NULL,
    joined_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE NOT NULL,
    withdrawn_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_members_grade  CHECK (grade IN ('GENERAL', 'VIP')),
    CONSTRAINT ck_members_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE TABLE staff (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id      VARCHAR(30)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    name          VARCHAR(50)  NOT NULL,
    department    VARCHAR(200) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    active        BOOLEAN      NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_staff_role CHECK (role IN ('ADMIN', 'OPERATOR'))
);

CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT      NOT NULL,
    status         VARCHAR(20) NOT NULL,
    product_amount BIGINT      NOT NULL,
    delivery_fee   BIGINT      NOT NULL,
    total_amount   BIGINT      NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    paid_at        TIMESTAMP WITH TIME ZONE,
    expired_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_orders_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'EXPIRED')),
    CONSTRAINT ck_orders_amount CHECK (product_amount >= 0 AND delivery_fee >= 0 AND total_amount = product_amount + delivery_fee)
);

CREATE TABLE order_lines (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT       NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    unit_price   BIGINT       NOT NULL,
    quantity     INT          NOT NULL,
    CONSTRAINT fk_order_lines_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_order_lines_value CHECK (unit_price >= 0 AND quantity >= 1)
);

CREATE TABLE deliveries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT      NOT NULL UNIQUE,
    status       VARCHAR(20) NOT NULL,
    fee          BIGINT      NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    shipped_at   TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_deliveries_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_deliveries_status CHECK (status IN ('READY', 'SHIPPED', 'DELIVERED'))
);

CREATE TABLE refunds (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id               BIGINT       NOT NULL,
    amount                 BIGINT       NOT NULL,
    partial                BOOLEAN      NOT NULL,
    reason                 VARCHAR(200) NOT NULL,
    status                 VARCHAR(20)  NOT NULL,
    delivery_fee_deduction BIGINT,
    refunded_amount        BIGINT,
    requested_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_refunds_status CHECK (status IN ('REQUESTED', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_refunds_amount CHECK (amount > 0)
);
